export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FECTH_TAGS = "FETCH_TAGS";
export const FILTER_BY_TAG = "FILTER_BY_TAG";

export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const UPDATE_ARTICLE_LIST = "UPDATE_ARTICLE_LIST";

export const FAIL_TO_FETCH_USER_INFO = "FAIL_TO_FETCH_USER_INFO";
export const FAIL_TO_FETCH_ARTICLE = "FAIL_TO_FETCH_ARTICLE";