export const FECTH_TAGS = "FETCH_TAGS";

export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const FAIL_TO_FETCH_USER_INFO = "FAIL_TO_FETCH_USER_INFO";

export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const ADD_USERNAME_TO_FETCH = "ADD_USERNAME_TO_FETCH";
export const FETCH_USER_ARTICLE = "FETCH_USER_ARTICLE";
export const FILTER_BY_TAG = "FILTER_BY_TAG";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const FAIL_TO_FETCH_ARTICLE = "FAIL_TO_FETCH_ARTICLE";

export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const UPDATE_COMMENT = "UPDATE_COMMENT";