export const FECTH_TAGS = 'FETCH_TAGS';

export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const FAIL_TO_FETCH_USER_INFO = 'FAIL_TO_FETCH_USER_INFO';
export const FOLLOWING_AUTHORS = 'FOLLOWING_AUTHORS';
export const USER_FAVORITED_ARTICLES = 'USER_FAVORITED_ARTICLES';

export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const ADD_USERNAME_TO_FETCH = 'ADD_USERNAME_TO_FETCH';
export const FETCH_USER_ARTICLE = 'FETCH_USER_ARTICLE';
export const FILTER_BY_TAG = 'FILTER_BY_TAG';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const FAIL_TO_FETCH_ARTICLE = 'FAIL_TO_FETCH_ARTICLE';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';

export const FETCH_AUTHOR_PROFILE = 'FETCH_AUTHOR_PROFILE';
export const REFETCH_AUTHOR_BY_ACTION = 'REFETCH_AUTHOR_BY_ACTION';

export const LIKE_UNLIKE_ARTICLE = 'LIKE_UNLIKE_ARTICLE';
export const FETCH_FAVORITED_ARTICLES = 'FETCH_FAVORITED_ARTICLES';
export const REFETCH_FAVORITED_ARTICLES = 'REFETCH_FAVORITED_ARTICLES';
